stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Building the project..."
  tags:
    - nest-runner

test-job:
  stage: test
  script:
    - echo "Running tests..."
  tags:
    - nest-runner

deploy-job:
  stage: deploy
  script:
    - echo "Deploying to OpenNebula"
  tags:
    - nest-runner
