stages:
  - build
  - test
  - deploy

nest-runner:
  build:
    stage: build
    script:
      - echo "Building the project..."
      - echo "Testing the cron job execution"
  
  test:
    stage: test
    script:
      - echo "Running tests..."
  
  
  deploy:
    stage: deploy
    script:
      - echo "Deploying to OpenNebula"
      - echo "This is a test"
