# docker-compose.yml
version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scoring
    ports:
      - "5432:5432"
