services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scoring
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d scoring"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
    volumes:
      - ./Logs:/Logs
    stdin_open: true
    tty: true
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: scoring
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"

  webserver:
    build:
      context: ./web/front-end
    ports:
      - "80:80"
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: scoring
      BACKEND_HOST: backend
      BACKEND_PORT: 8080
    depends_on:
      postgres:
        condition: service_healthy
