version: '3.1'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scoring
    ports:
      - "5432:5432"

  scoring-engine:
    build:
      context: .
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: root
      DATABASE_PASSWORD: root
      DATABASE_NAME: scoring
    depends_on:
      - postgres
