[package]
name = "nest_backend"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.0-rc.2", features = ["json"] } # RESTful API
diesel = { version = "2.0.0", features = ["postgres","r2d2","chrono"] } # Database interaction
dotenvy = "0.15"