# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install Go dependencies
      run: go mod tidy

    - name: Install templ
      run: go install github.com/a-h/templ@latest
      
    - name: Run Go Templating
      run: templ -d . -o . -e .tmpl
      
    - name: Build Project
      run: go build -o scoring-engine
      
    - name: Test Project
      run: go test ./...
